// 🥠 Fortune Cookie Messages - 200+ fortunes across 5 personalities

const fortunes = {
  // 🧘 ZEN MASTER - Calm, cryptic wisdom
  zen: [
    "The bug you seek is within yourself.",
    "Empty your mind. The solution will come.",
    "This refactor will bring you peace.",
    "The function you need is already written.",
    "Let go of your attachment to clean code.",
    "In silence, the answer reveals itself.",
    "Your next commit will be your best.",
    "The console.log you seek is already there.",
    "A variable named well is a variable understood.",
    "The path to production is paved with tests.",
    "One line of documentation saves ten of debugging.",
    "The bug that cannot be reproduced is the bug that cannot be fixed.",
    "Code is read more than it is written.",
    "A comment is worth a thousand lines of code.",
    "In the beginning, there was the void. Then came the first commit.",
    "The feature you desire is already in another library.",
    "Merge conflicts are illusions created by the ego.",
    "The simplest solution is often the best solution.",
    "Your code is a reflection of your mind.",
    "To understand recursion, one must first understand recursion.",
    "The documentation you seek is in the source code.",
    "A junior developer asks 'how'. A senior asks 'why'.",
    "The perfect code is the code that ships.",
    "Every bug is a teacher in disguise.",
    "The commit that is feared is the commit that must be made.",
    "Your IDE is a garden. Tend to it.",
    "The error message is not your enemy, but your guide.",
    "A function should do one thing, and do it well.",
    "The legacy code was once the new code.",
    "In the midst of complexity, find simplicity.",
    "The variable that is global is the variable that causes suffering.",
    "A good name is worth a thousand comments.",
    "The test you skip today is the bug you fix tomorrow.",
    "Code is poetry written in logic.",
    "The deadline is an illusion, but the technical debt is real.",
    "Your linter is your friend, not your foe.",
    "The code review is a mirror reflecting your craft.",
    "A monolith divided against itself cannot stand.",
    "The microservice you seek may be a function in disguise.",
    "To delete code is to add value.",
  ],

  // 🎤 HYPE MAN - Over-the-top encouragement
  hype: [
    "THIS COMMIT IS ABOUT TO BE LEGENDARY!",
    "YOU'RE ABSOLUTELY CRUSHING IT!",
    "NEXT PR = INSTANT MERGE!",
    "BRO! THIS CODE IS FIRE! 🔥",
    "YOU'RE ON A ROLL! KEEP GOING!",
    "THIS FUNCTION IS ABOUT TO CHANGE THE GAME!",
    "LEGENDARY STATUS: ACHIEVED!",
    "THE CODEBASE IS NOT READY FOR THIS ENERGY!",
    "ABSOLUTE SCENES RIGHT NOW!",
    "THIS IS THE COMMIT THAT CHANGES EVERYTHING!",
    "SOMEONE CALL THE FIRE DEPARTMENT! 🚒",
    "YOU'RE CARRYING THE WHOLE TEAM RIGHT NOW!",
    "MVP PERFORMANCE! MOST VALUABLE PROGRAMMER!",
    "THIS CODE IS GOING STRAIGHT TO PRODUCTION!",
    "NO BUGS CAN STOP YOU TODAY!",
    "YOU'RE IN THE ZONE! THE FLOW STATE!",
    "THE GITHUB GODS ARE SMILING UPON YOU!",
    "ABSOLUTE UNIT OF A COMMIT!",
    "SENDING THIS STRAIGHT TO THE HALL OF FAME!",
    "YOU'RE NOT JUST CODING, YOU'RE CREATING ART!",
    "NEXT LEVEL ACHIEVEMENT UNLOCKED!",
    "THE COMMIT GRAPH LOOKS LIKE A HEARTBEAT BECAUSE YOU'RE ALIVE!",
    "ZERO COMPROMISE, MAXIMUM EFFORT!",
    "YOU'RE NOT A DEVELOPER, YOU'RE A CODE WIZARD! 🧙‍♂️",
    "THIS IS THE KIND OF CODE THAT GETS REMEMBERED!",
    "BREAKING NEWS: YOU'RE AMAZING!",
    "THE STARS HAVE ALIGNED FOR THIS COMMIT!",
    "YOU'RE MAKING HISTORY ONE LINE AT A TIME!",
    "ABSOLUTELY UNSTOPPABLE MOMENTUM!",
    "THE GITHUB STARS ARE INCOMING!",
    "SOMEONE GET THIS PERSON A COFFEE AND A RAISE!",
    "THIS IS WHAT PEAK PERFORMANCE LOOKS LIKE!",
    "YOU'RE NOT JUST SHIPPING CODE, YOU'RE SHIPPING DREAMS!",
    "THE TERMINAL IS YOUR CANVAS AND YOU'RE PICASSO!",
    "SENDING POSITIVE VIBES TO YOUR COMPILER!",
    "YOU'RE LIVING IN THE FUTURE WITH THIS CODE!",
    "ABSOLUTE MONSTER OF A DEVELOPER!",
    "THE CODE REVIEWERS WILL WEEP WITH JOY!",
    "LEGENDARY DIFF, EPIC CHANGES!",
    "YOU'RE THE GOAT! GREATEST OF ALL TERMINALS!",
  ],

  // 🔥 ROASTER - Brutal honesty
  roast: [
    "This variable name screams 'I gave up'",
    "Your code has more issues than a magazine stand",
    "Is this function a novel? Because it's 500 lines long",
    "Function name `doStuff`? Really? That's the best you got?",
    "I've seen clearer comments in ancient hieroglyphics",
    "This code works by coincidence, not by design",
    "Your git history tells a story... a tragic one",
    "This import section needs its own zip code",
    "This regex could summon demons. Please don't deploy it.",
    "I've seen spaghetti code, but this is a whole Italian restaurant",
    "Your naming convention is... inconsistent at best",
    "This nested if statement has more layers than an onion",
    "The console.log statements are having a party in production",
    "Your indentation is giving me an existential crisis",
    "This function has more parameters than a spaceship cockpit",
    "I've seen clearer variable names in obfuscated code",
    "Your code style is... eclectic",
    "This try-catch block is catching feelings, not errors",
    "The TODO comments are older than some programming languages",
    "Your variable naming strategy appears to be 'keyboard smash'",
    "This switch statement has more cases than a detective novel",
    "Your code comments are like 'here be dragons' but less helpful",
    "I've seen more organization in a toddler's toy box",
    "This callback hell is deeper than my commitment issues",
    "Your type definitions are... optimistic",
    "This global variable is having an identity crisis",
    "Your error handling strategy appears to be 'hope for the best'",
    "I've seen more structure in a Jackson Pollock painting",
    "This function signature is longer than my grocery list",
    "Your code is like a puzzle, except all the pieces are from different puzzles",
    "This magic number is so magical it appeared in three other files",
    "Your async/await usage is... creative",
    "I've seen clearer logic in Choose Your Own Adventure books",
    "This code smells like... technical debt",
    "Your variable scope is wider than the Grand Canyon",
    "This recursion doesn't know when to stop. Kind of like you.",
    "I've seen better error messages from Windows 98",
    "Your code architecture is... avant-garde",
    "This copy-paste job is giving me déjà vu",
    "Your git commit messages are like abstract poetry",
  ],

  // 🔮 NOSTRADAMUS - Mysterious predictions
  nostradamus: [
    "In three days, a bug will emerge from line 42",
    "Your next PR will spark a 47-comment debate",
    "A junior dev will break this within the week",
    "This code will be rewritten before the month ends",
    "You will spend 4 hours on a one-line fix",
    "A mysterious StackOverflow answer will save you",
    "Your next standup will run over by 15 minutes",
    "The client will ask for this feature... tomorrow",
    "The test you skip today will fail in production... next Friday",
    "A code review comment will change your perspective",
    "The library you're using will release a breaking change... soon",
    "Someone will ask 'why did we do it this way?' in 6 months",
    "Your weekend deployment will teach you many lessons",
    "The intern will ask about this code during their first week",
    "A security vulnerability scan will find... something interesting",
    "The product manager will request a 'small change' that takes 3 weeks",
    "Your clever optimization will become the source of a mysterious bug",
    "The documentation you didn't write will be requested... repeatedly",
    "A failed test in CI will teach you about race conditions",
    "The 'temporary' solution will celebrate its first birthday",
    "Someone will try to refactor this... and regret it",
    "The legacy system you're replacing will outlive your new system",
    "Your Friday 5pm commit will be remembered... not fondly",
    "The edge case you ignored will become the main use case",
    "A performance issue will emerge when you least expect it",
    "The quick fix will require 3 more quick fixes",
    "Someone will 'just test in production'... and learn",
    "The hotfix will become a permanent fixture",
    "Your 'simple' change will touch 15 files",
    "The code you wrote at 3am will confuse you at 9am",
    "A user will find a way to break this that you never imagined",
    "The technical debt collector is coming... with interest",
    "Your clever hack will be someone's debugging nightmare",
    "The 'final' version will be version 1 of 47",
    "A mysterious bug will appear only on Tuesdays",
    "The API you're calling will change... without warning",
    "Your optimistic timeline will meet... reality",
    "The feature flag will remain on longer than intended",
    "Someone will grep for TODO and find your name everywhere",
    "The demo will work perfectly... until the actual demo",
  ],

  // 🎭 SHAKESPEARE - Dramatic flair
  shakespeare: [
    "To deploy or not to deploy, that is the question",
    "Alas, poor function, I knew thee well",
    "Something wicked this way comes... it's your build",
    "The code is dark and full of errors",
    "A bug by any other name would smell as sweet",
    "All the world's a repo, and all the devs merely players",
    "To debug perchance to dream",
    "Once more unto the merge conflict, dear friends",
    "Friends, Romans, countrymen, lend me your code reviews",
    "The quality of code is not strained, it drops like the gentle rain",
    "Now is the winter of our discontent, made glorious summer by this refactor",
    "A horse! A horse! My kingdom for a working dependency!",
    "The fault, dear Brutus, is not in our stars, but in our syntax",
    "We are such stuff as dreams are made on, and our little life is rounded with a sleep... and a commit",
    "Cowards die many times before their deaths; the valiant never taste of merge conflicts",
    "This above all: to thine own code be true",
    "Though she be but little, she is fierce... this microservice, I mean",
    "Parting is such sweet sorrow, said every developer deleting code",
    "The lady doth protest too much, methinks... about this pull request",
    "Brevity is the soul of wit, and of good functions",
    "Uneasy lies the head that wears the crown... of technical debt",
    "Good night, good night! Parting is such sweet sorrow... until the next sprint",
    "What's in a name? That which we call a bug by any other name would smell as foul",
    "The better part of valor is discretion... in code reviews",
    "If code be the food of love, commit on",
    "O brave new world, that has such libraries in't!",
    "The course of true development never did run smooth",
    "Lord, what fools these mortals be... who don't write tests",
    "Love looks not with the eyes but with the mind... and neither should code review",
    "All that glitters is not gold... all that passes CI is not bug-free",
    "Hell is empty and all the devs are here... in this meeting",
    "We know what we are, but know not what we may be... after this refactor",
    "The evil that men do lives after them; the good is oft interred with their bones... and their git history",
    "There are more things in heaven and earth, Horatio, than are dreamt of in your documentation",
    "The readiness is all... for production deployment",
    "To thine own self be true, and it must follow, as the night the day, thou canst not then be false to any code review",
    "Now cracks a noble heart. Good night, sweet PR, and flights of angels sing thee to thy merge",
    "O, what authority and show of truth... can this test suite provide?",
    "The play's the thing wherein I'll catch the conscience of the... compiler",
    "There is nothing either good or bad, but thinking makes it so... except for global variables",
  ],

  // 🎪 EASTER EGGS - Special occasions
  easterEggs: {
    fridayDeploy: [
      "🚨 FRIDAY DEPLOYMENT DETECTED 🚨",
      "It's Friday. Are you SURE about this?",
      "The weekend is calling... but so is the pager",
      "Friday deploy: bold strategy, Cotton",
      "Your future self will remember this... with regret",
    ],
    lateNight: [
      "It's 3am. The code is speaking to you. That's not normal.",
      "Sleep is for the weak. And the bug-free.",
      "The night is dark and full of semicolons",
      "Coffee levels: critical",
      "Your circadian rhythm has left the chat",
    ],
    firstCommit: [
      "FIRST COMMIT OF THE DAY! YOU'RE ALREADY WINNING!",
      "The early bird catches the bug",
      "Rise and grind! The repo awaits!",
      "Day 1 of being awesome at coding",
      "The blank slate. The endless possibility. The inevitable bugs.",
    ],
    elevenEleven: [
      "🕚 11:11 - Make a wish... Your next build will pass",
      "The coding gods are listening at 11:11",
      "Wish for fewer bugs. Wish harder.",
      "11:11 - The most mystical minute for developers",
      "Time to manifest that bug-free release",
    ],
  },
};

module.exports = fortunes;
